export const FETCH_POSTS_REQUESTED = "FETCH_POSTS_REQUESTED";
export const FETCH_POSTS_SUCCEEDED = "FETCH_POSTS_SUCCEEDED";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const FETCH_POSTS_DISCONNECTED = "FETCH_POSTS_DISCONNECTED";
export const FETCH_POSTS_RESET = "FETCH_POSTS_RESET";